#!/bin/bash
# utility functions that are useable and useful not only in a packing building environment

while read -r f;do
  . "${f}"
done < <(find '__{{install_directory}}__/scripts/helpers' -type f)